=== msd1kpei/OR08-DataFeedTrade/OR08-DataFeedTrade/xsd/DataTrade-request.xsd
<?xml version='1.0' encoding='windows-1252'?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.kpei.co.id/DataTradeRequest" targetNamespace="http://www.kpei.co.id/DataTradeRequest" elementFormDefault="qualified">
   <xsd:include schemaLocation="MiddlewareHeader.xsd"/>
   <xsd:include schemaLocation="ExpandableVariable.xsd"/>
   <xsd:element name="DataTrade">
      <xsd:annotation>
         <xsd:documentation>
        A sample element
      </xsd:documentation>
      </xsd:annotation>
      <xsd:complexType>
         <xsd:sequence>
            <xsd:element name="header" type="middlewareHeader"/>
            <xsd:element name="isDummy" type="xsd:string"/>
            <xsd:element name="session" type="tSession" maxOccurs="1" minOccurs="1"/>
            <xsd:element name="body">
               <xsd:complexType>
                  <xsd:sequence maxOccurs="unbounded">
                     <xsd:element name="trade">
                        <xsd:complexType>
                           <xsd:sequence>
                              <xsd:element name="tradeNumber" type="xsd:string"/>
                              <xsd:element name="sellerBuyer">
                                 <xsd:complexType>
                                    <xsd:sequence>
                                       <xsd:element name="sellerBroker" type="xsd:string"/>
                                       <xsd:element name="stockCode" type="xsd:string"/>
                                       <xsd:element name="boardCode" type="xsd:string"/>
                                       <xsd:element name="tradeNumber" type="xsd:string"/>
                                       <xsd:element name="tradeDate" type="xsd:date"/>
                                       <xsd:element name="buyerBroker" type="xsd:string"/>
                                    </xsd:sequence>
                                 </xsd:complexType>
                              </xsd:element>
                              <xsd:element name="tradeDate" type="xsd:date"/>
                              <xsd:element name="sessionTrade" type="xsd:string"/>
                              <xsd:element name="boardCode" type="xsd:string"/>
                              <xsd:element name="sellerBroker" type="xsd:string"/>
                              <xsd:element name="sellerClient" type="xsd:string"/>
                              <xsd:element name="sellerType" type="xsd:string"/>
                              <xsd:element name="brokerCode" type="xsd:string"/>
                              <xsd:element name="brokerClient" type="xsd:string"/>
                              <xsd:element name="brokerType" type="xsd:string"/>
                              <xsd:element name="stockCode" type="xsd:string"/>
                              <xsd:element name="volume" type="xsd:string"/>
                              <xsd:element name="price" type="xsd:string"/>
                           </xsd:sequence>
                        </xsd:complexType>
                     </xsd:element>
                  </xsd:sequence>
               </xsd:complexType>
            </xsd:element>
            <xsd:element name="ext" type="expandableVariable"/>
         </xsd:sequence>
      </xsd:complexType>
   </xsd:element>
   <xsd:simpleType name="tSession">
      <xsd:restriction base="xsd:string">
         <xsd:minLength value="1"/>
      </xsd:restriction>
   </xsd:simpleType>
</xsd:schema>

=== msd1kpei/OR08-DataFeedTrade/OR08-DataFeedTrade/public_html/Transformation_1-Source.xml
<?xml version='1.0' encoding='UTF-8'?>
<DataTrade xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.kpei.co.id/DataTradeRequest file:/C:/jdeveloper-doc/OR08-DataFeedTrade/xsd/DataTrade-request.xsd" xmlns="http://www.kpei.co.id/DataTradeRequest">
   <header id="id1">
      <asAt>2011-01-17T19:52:56.359</asAt>
      <source>source2</source>
   </header>
   <body>
      <trade>
         <tradeNumber>tradeNumber3</tradeNumber>
         <sellerBuyer>
            <sellerBroker/>
            <stockCode/>
            <boardCode/>
            <tradeNumber/>
            <tradeDate/>
            <buyerBroker/>
         </sellerBuyer>
         <tradeDate>2011-01-17</tradeDate>
         <sessionTrade>sessionTrade4</sessionTrade>
         <boardCode>boardCode5</boardCode>
         <sellerBroker>sellerBroker6</sellerBroker>
         <sellerClient>sellerClient7</sellerClient>
         <sellerType>sellerType8</sellerType>
         <brokerCode>brokerCode9</brokerCode>
         <brokerClient>brokerClient10</brokerClient>
         <brokerType>brokerType11</brokerType>
         <stockCode>stockCode12</stockCode>
         <volume>volume13</volume>
         <price>price14</price>
      </trade>
   </body>
   <ext>
      <value id="id15">string16</value>
      <value id="id17">string18</value>
      <value id="id19">string20</value>
   </ext>
</DataTrade>
